image: omidtaheri/android-docker:1.0.0


before_script:
  - chmod +x ./gradlew
  - touch ./info.txt
  - echo "Build date          $(date)"                >> ./info.txt
  - echo "Git branch          ${CI_COMMIT_REF_NAME}"  >> ./info.txt
  - echo "Git commit          ${CI_COMMIT_SHA}"       >> ./info.txt
  - echo "Gitlab pipeline     ${CI_PIPELINE_ID}"      >> ./info.txt


stages: 
  - code_analysis
  - build
  - test
  - doc
  - deploy

cache:
  key: ${CI_PROJECT_ID}
  paths:
   - .gradle/

lint:
  stage: code_analysis
  script:
   - ./gradlew :app:lint 

  allow_failure: true

  artifacts:
    name: "reports_${CI_PROJECT_NAME}_${CI_BUILD_REF_NAME}"
    paths : 
     - app/build/reports/lint/
     - ./info.txt

  when: always


 
build_debug :
  stage: build
  script:
   - ./gradlew assembleDebug
   - mv app/build/outputs/apk/debug/app-debug.apk ./app-android-debug-v${CI_COMMIT_SHA}.apk

  artifacts:
    paths :
     - ./*.apk
     - ./info.txt


build_release :
  stage: build

  only:
    - master
    - release

  script:
    - ./gradlew assembleRelease
    - mv app/build/outputs/aar/app-android-release.aar ./app-android-release-v${CI_COMMIT_SHA}.aar
    - mv ./sdk/build/outputs/logs/manifest-merger-android-release-report.txt .
    - mv ./sdk/build/outputs/mapping/android/release/* .

  artifacts:
    paths :
     - ./*.aar
     - ./*.txt


test :
  stage: test
  script:
    - ./gradlew :app:test
  rules:
     - if: $CI_PIPELINE_SOURCE == "merge_request_event"

 
   
document : 
  stage: doc
  script:
     - ./gradlew dokka
  allow_failure: true

  artifacts:
    paths : 
     - app/build/javadoc/
