# The name of our workflow
name: Build
# Trigger on every push
on: 
   push:
      branches:
         - main
 

jobs:
   # The name of job
  build_debug :
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Create file
        run: |
         echo "sdk.dir=$ANDROID_HOME"                                          > ./local.properties
         echo "signing.key.alias=${{ secrets.SIGN_KEY_ALIAS }}"                >> ./local.properties
         echo "signing.key.password=${{ secrets.SIGN_KEY_PASS }}"              >> ./local.properties
         echo "signing.store.file=.${{ secrets.SIGN_STORE_FILE }}"              >> ./local.properties
         echo "signing.store.password=${{ secrets.SIGN_STORE_PASS }}"          >> ./local.properties
         mkdir -p $(dirname ${{ secrets.SIGN_STORE_FILE }}) && touch ${{ secrets.SIGN_STORE_FILE }}
         echo ${{ secrets.KEY_STORE_FILE_BASE64 }} | base64 --decode > ${{ secrets.SIGN_STORE_FILE }}
 
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
            java-version: 11
      - name: Exec permissions
        run: chmod +x ./gradlew
      - name: Build the debug app
        run: ./gradlew assembleDebug
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: build_debug_output
          path: app/build/outputs/apk/debug/app-debug.apk
 
   # The name of job
  test :
    runs-on: ubuntu-latest
    needs:
      - build_debug
    steps:
      - uses: actions/checkout@v2
      - name: Create file
        run: |
         echo "sdk.dir=${{ secrets.SDK_DIR }}"                                 > ./local.properties
         echo "signing.key.alias=${{ secrets.SIGN_KEY_ALIAS }}"                >> ./local.properties
         echo "signing.key.password=${{ secrets.SIGN_KEY_PASS }}"              >> ./local.properties
         echo "signing.store.file=.${{ secrets.SIGN_STORE_FILE }}"              >> ./local.properties
         echo "signing.store.password=${{ secrets.SIGN_STORE_PASS }}"          >> ./local.properties
         mkdir -p $(dirname ${{ secrets.SIGN_STORE_FILE }}) && touch ${{ secrets.SIGN_STORE_FILE }}
         echo ${{ secrets.KEY_STORE_FILE_BASE64 }} | base64 --decode > ${{ secrets.SIGN_STORE_FILE }}
         
         
      - name: Set Up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Exec permissions
        run: chmod +x ./gradlew
      - name: Run Tests   
        run: ./gradlew :app:test
 
  build_release :
     runs-on: ubuntu-latest
     steps:  
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Create file
        run: |
         echo "sdk.dir=$ANDROID_HOME"                                          > ./local.properties
         echo "signing.key.alias=${{ secrets.SIGN_KEY_ALIAS }}"                >> ./local.properties
         echo "signing.key.password=${{ secrets.SIGN_KEY_PASS }}"              >> ./local.properties
         echo "signing.store.file=.${{ secrets.SIGN_STORE_FILE }}"              >> ./local.properties
         echo "signing.store.password=${{ secrets.SIGN_STORE_PASS }}"          >> ./local.properties
         mkdir -p $(dirname ${{ secrets.SIGN_STORE_FILE }}) && touch ${{ secrets.SIGN_STORE_FILE }}
         echo ${{ secrets.KEY_STORE_FILE_BASE64 }} | base64 --decode > ${{ secrets.SIGN_STORE_FILE }}
       
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
            java-version: 11
      - name: Exec permissions
        run: chmod +x ./gradlew
      - name: Build the release app
        run: ./gradlew assembleRelease
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: build_release_output
          path: app/build/outputs/apk/release/
