# The name of our workflow
name: Build
# Trigger on every push
on: 
   push:
      branches:
         - main
 

jobs:
   # The name of job
  build_debug :
    runs-on: ubuntu-latest
    steps:
      - name: Create file
      run: |
         echo First        > other.txt
         echo Second Line >> other.txt
         echo Third       >> other.txt

      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
            java-version: 11
            
      - name: Exec permissions
        run: chmod +x ./gradlew
        
      - name: Build the app
        run: ./gradlew assembleDebug
        
      - name: Move  Apk
        run:  mv app/build/outputs/apk/app-debug.apk ./app-android-debug-v${CI_COMMIT_SHA}.apk

  tests :
      needs: 
       - build_debug
      runs-on: ubuntu-latest
      steps:
       - name: Checkout the code
         uses: actions/checkout@v2
         
       - name: Run tests
         run: ./gradlew :app:test


  # The name of job
  build_release :
    runs-on: ubuntu-latest
    needs:
    - tests
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: Build the app
        run: ./gradlew assembleRelease
        
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: release.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
          
      - name: Upload artifact2
        uses: actions/upload-artifact@master
        with:
          name: mapping.txt
          path: app/build/outputs/mapping/release/mapping.txt


  docker-run:
    runs-on: ubuntu-latest
    container:
      image: omidtaheri/android-docker:1.0.0
    steps:
    - uses: actions/checkout@v2
    
  build-apk:
    name: Generate apk
    runs-on: ubuntu-latest
    needs:
    - tests
    steps:
    - uses: actions/checkout@v1

    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Generate apk
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: build-output
        path: app/build/outputs/apk/debug/app-debug.apk